[package]
name = "koekbar"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.3.1"
chrono = "0.4.40"
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_12"] }
gtk4-layer-shell = "0.5.0"
mpris = "2.0.1"
tokio = { version = "1.44.2", features = ["full"] }
